Scenes:
  - Path: "Paper/Platformer/Platformer.scene"
    SceneGuid: "a5e9b072-cbd2-4960-8f09-d2016fc1d12b"
    Enabled: true
    $id: 2
Config: 1
OutputDirectory: "Builds/v5/MacOS"
PackagingMode: 1
AssetMode: 1
MaxPakSizeMB: 2048
PlatformProfiles:
  - Platform: 2
    SelfContained: true
    PublishTrimmed: false
    WindowWidth: 1280
    WindowHeight: 720
    $id: 3
    $type: "Prowl.Editor.Build.DesktopBuildProfile, Prowl.Editor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
$id: 1
$type: "Prowl.Editor.BuildSettings, Prowl.Editor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
